# What is PyTorch?

It’s a Python-based scientific computing package targeted at two sets of audiences:
* A replacement for NumPy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed

## 1) Getting Started
### Tensors
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Checking the version of pytorch: We'll use Pytorch 1.4


If you already have a older version of pytorch installed, you can update pytorch with command: 

`conda update pytorch torchvision -c pytorch`

In [2]:
print(torch.__version__)

1.4.0


Construct a 5x3 matrix, uninitialized:

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.9618e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.5169e-14,  2.3558e+27],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -3.5461e+15, -3.2522e-10],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3956, 0.2620, 0.5641],
        [0.9581, 0.5659, 0.8615],
        [0.0849, 0.3340, 0.7662],
        [0.4360, 0.5558, 0.1640],
        [0.6529, 0.3960, 0.9632]])


Construct a matrix filled with zeros and of dtype long:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [6]:
x = torch.tensor([5, 3])
print(x)

tensor([5, 3])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[-0.2627, -0.3070, -0.6550],
        [ 1.0828, -2.7412, -0.4486],
        [-0.4631, -0.8507, -1.2115],
        [-0.4609,  0.8358, -2.0607],
        [ 1.0000,  1.2947,  1.3301]])


Get its size:

In [8]:
print(x.size())

torch.Size([5, 3])


* NOTE:
>`torch.Size` is in fact a tuple, so it supports all tuple operations.

In [9]:
print(x.size()[0])

5


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5975,  0.4371, -0.4904],
        [ 1.3227, -1.9772,  0.0046],
        [ 0.0462, -0.3141, -1.1191],
        [-0.2433,  1.3932, -1.4454],
        [ 1.7206,  1.3869,  2.3224]])


Addition: syntax 2

In [11]:
print(torch.add(x, y))

tensor([[ 0.5975,  0.4371, -0.4904],
        [ 1.3227, -1.9772,  0.0046],
        [ 0.0462, -0.3141, -1.1191],
        [-0.2433,  1.3932, -1.4454],
        [ 1.7206,  1.3869,  2.3224]])


Addition: providing an output tensor as argument

In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5975,  0.4371, -0.4904],
        [ 1.3227, -1.9772,  0.0046],
        [ 0.0462, -0.3141, -1.1191],
        [-0.2433,  1.3932, -1.4454],
        [ 1.7206,  1.3869,  2.3224]])


Addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5975,  0.4371, -0.4904],
        [ 1.3227, -1.9772,  0.0046],
        [ 0.0462, -0.3141, -1.1191],
        [-0.2433,  1.3932, -1.4454],
        [ 1.7206,  1.3869,  2.3224]])


* NOTE:
>Any operation that mutates a tensor in-place is post-fixed with an `_`.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([-0.3070, -2.7412, -0.8507,  0.8358,  1.2947])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2997])
-1.299719214439392


**Read later:**
>100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html).

## 2) NumPy bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 3) CUDA Tensors
Tensors can be moved onto any device using the ``.to`` method.

In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!